### Approaching methods
1.Content Based
2. Filtering Based

### Filtering Method

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
Movies = pd.read_csv('movies.csv')
Ratings = pd.read_csv('ratings.csv')

In [3]:
Movies.head(-1)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9736,193579,Jon Stewart Has Left the Building (2015),Documentary
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation

In [4]:
Ratings.head(-1)

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100830     610   166528     4.0  1493879365
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352

[100835 rows x 4 columns]

In [5]:
Movies.shape

(9742, 3)

In [6]:
Ratings.shape

(100836, 4)

In [8]:
df = pd.merge(Movies, Ratings, on = 'movieId')

In [9]:
def Convert(title):
    return title.lower()

In [10]:
df['title'] = df['title'].apply(Convert)

In [12]:
## Calculating the mean rating of all movies
grp = df.groupby('title')['rating'].mean().sort_values(ascending = False)

title
tenchi muyô! in love (1996)             5.0
five senses, the (1999)                 5.0
live nude girls (1995)                  5.0
little murders (1971)                   5.0
trailer park boys (1999)                5.0
                                       ...
case 39 (2009)                          0.5
pearl jam twenty (2011)                 0.5
killer shrews, the (1959)               0.5
3 dev adam (three giant men) (1973)     0.5
uncle nino (2003)                       0.5
Name: rating, Length: 9719, dtype: float64

In [13]:
grp.head()

title
tenchi muyô! in love (1996)    5.0
five senses, the (1999)        5.0
live nude girls (1995)         5.0
little murders (1971)          5.0
trailer park boys (1999)       5.0
Name: rating, dtype: float64

In [15]:
dfNew = pd.DataFrame(df.groupby('title')['rating'].mean())
dfNew['NumRatings'] = df.groupby('title')['rating'].count()

In [16]:
dfNew

                                             rating  NumRatings
title
'71 (2014)                                 4.000000           1
'burbs, the (1989)                         3.176471          17
'hellboy': the seeds of creation (2004)    4.000000           1
'night mother (1986)                       3.000000           1
'round midnight (1986)                     3.500000           2
...                                             ...         ...
zootopia (2016)                            3.890625          32
zulu (1964)                                4.000000           4
zulu (2013)                                1.500000           1
¡three amigos! (1986)                      3.134615          26
à nous la liberté (freedom for us) (1931)  1.000000           1

[9719 rows x 2 columns]

In [17]:
# User who gives rating to a movie will be displayed with columns as movie names
movieTitle = df.pivot_table(index = 'userId', columns = 'title', values = 'rating')

In [18]:
movieTitle.head(20)

title,'71 (2014),"'burbs, the (1989)",'hellboy': the seeds of creation (2004),'night mother (1986),'round midnight (1986),'salem's lot (2004),'til there was you (1997),'tis the season for love (2015),(500) days of summer (2009),*batteries not included (1987),...,zookeeper (2011),zoolander (2001),zoolander 2 (2016),zoom (2006),zoom (2015),zootopia (2016),zulu (1964),zulu (2013),¡three amigos! (1986),à nous la liberté (freedom for us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
cols = list(movieTitle.columns)
cols

["'71 (2014)",
 "'burbs, the (1989)",
 "'hellboy': the seeds of creation (2004)",
 "'night mother (1986)",
 "'round midnight (1986)",
 "'salem's lot (2004)",
 "'til there was you (1997)",
 "'tis the season for love (2015)",
 '(500) days of summer (2009)',
 '*batteries not included (1987)',
 '...all the marbles (1981)',
 '...and justice for all (1979)',
 '00 schneider - jagd auf nihil baxter (1994)',
 '1-900 (06) (1994)',
 '10 (1979)',
 '10 cent pistol (2015)',
 '10 cloverfield lane (2016)',
 '10 items or less (2006)',
 '10 things i hate about you (1999)',
 '10 years (2011)',
 '10,000 bc (2008)',
 '100 girls (2000)',
 '100 streets (2016)',
 '101 dalmatians (1996)',
 '101 dalmatians (one hundred and one dalmatians) (1961)',
 "101 dalmatians ii: patch's london adventure (2003)",
 '101 reykjavik (101 reykjavík) (2000)',
 '102 dalmatians (2000)',
 '10th & wolf (2006)',
 '10th kingdom, the (2000)',
 '10th victim, the (la decima vittima) (1965)',
 '11\'09"01 - september 11 (2002)',
 '11:14 (2003)',
 '11th hour, the (2007)',
 '12 angry men (1957)',
 '12 angry men (1997)',
 '12 chairs (1971)',
 '12 chairs (1976)',
 '12 rounds (2009)',
 '12 years a slave (2013)',
 '127 hours (2010)',
 '13 assassins (jûsan-nin no shikaku) (2010)',
 '13 ghosts (1960)',
 '13 going on 30 (2004)',
 '13 hours (2016)',
 '13 sins (2014)',
 '13 tzameti (2005)',
 '13th (2016)',
 '13th warrior, the (1999)',
 '1408 (2007)',
 '1492: conquest of paradise (1992)',
 '15 minutes (2001)',
 '16 blocks (2006)',
 '17 again (2009)',
 '1776 (1972)',
 '18 again! (1988)',
 '187 (one eight seven) (1997)',
 '1900 (novecento) (1976)',
 '1941 (1979)',
 '1969 (1988)',
 '1984 (nineteen eighty-four) (1984)',
 '2 days in new york (2012)',
 '2 days in paris (2007)',
 '2 days in the valley (1996)',
 '2 fast 2 furious (fast and the furious 2, the) (2003)',
 '2 guns (2013)',
 '20 dates (1998)',
 '20 feet from stardom (twenty feet from stardom) (2013)',
 '20 million miles to earth (1957)',
 '20,000 days on earth (2014)',
 '20,000 leagues under the sea (1916)',
 '20,000 leagues under the sea (1954)',
 '200 cigarettes (1999)',
 '2001 maniacs (2005)',
 '2001: a space odyssey (1968)',
 '2010: the year we make contact (1984)',
 '2012 (2009)',
 '2046 (2004)',
 '2048: nowhere to run (2017)',
 '21 (2008)',
 '21 and over (2013)',
 '21 grams (2003)',
 '21 jump street (2012)',
 '21 up (1977)',
 '22 jump street (2014)',
 '24 hour party people (2002)',
 '25th hour (2002)',
 '27 dresses (2008)',
 '28 days (2000)',
 '28 days later (2002)',
 '28 up (1985)',
 '28 weeks later (2007)',
 '3 days to kill (2014)',
 '3 dev adam (three giant men) (1973) ',
 '3 extremes (three... extremes) (saam gaang yi) (2004)',
 '3 idiots (2009)',
 '3 ninjas (1992)',
 '3 ninjas kick back (1994)',
 '3 ninjas knuckle up (1995)',
 '3 ninjas: high noon on mega mountain (1998)',
 '3 women (three women) (1977)',
 '3-iron (bin-jip) (2004)',
 '30 days of night (2007)',
 '30 minutes or less (2011)',
 '300 (2007)',
 '3000 miles to graceland (2001)',
 '300: rise of an empire (2014)',
 '31 (2016)',
 '35 up (1991)',
 '39 steps, the (1935)',
 '3:10 to yuma (1957)',
 '3:10 to yuma (2007)',
 '4 little girls (1997)',
 '4 months, 3 weeks and 2 days (4 luni, 3 saptamâni si 2 zile) (2007)',
 '40 days and 40 nights (2002)',
 '40-year-old virgin, the (2005)',
 '400 blows, the (les quatre cents coups) (1959)',
 '42 (2013)',
 '42 up (1998)',
 '42nd street (1933)',
 '47 ronin (2013)',
 '48 hrs. (1982)',
 '49 up (2005)',
 '5 centimeters per second (byôsoku 5 senchimêtoru) (2007)',
 '5 to 7 (2014)',
 '5,000 fingers of dr. t, the (1953)',
 '50 first dates (2004)',
 '50/50 (2011)',
 '52 pick-up (1986)',
 '54 (1998)',
 '6 days to air: the making of south park (2011)',
 '61* (2001)',
 '6th day, the (2000)',
 '6th man, the (sixth man, the) (1997)',
 '7 days in hell (2015)',
 '7 faces of dr. lao (1964)',
 '7th voyage of sinbad, the (1958)',
 '8 1/2 (8½) (1963)',
 '8 heads in a duffel bag (1997)',
 '8 mile (2002)',
 '8 seconds (1994)',
 '8 women (2002)',
 '8 ½ women (a.k.a. 8 1/2 women) (a.k.a. eight and a half women) (1999)',
 '800 bullets (800 balas) (2002)',
 '84 charing cross road (1987)',
 '8mm (1999)',
 '9 (2009)',
 '9 1/2 weeks (nine 1/2 weeks) (1986)',
 '9/11 (2002)',
 '96 minutes (2011) ',
 '964 pinocchio (1991)',
 '99 francs (2007)',
 '9to5: days in porn (a.k.a. 9 to 5: days in porn) (2008)',
 '[rec] (2007)',
 '[rec]² (2009)',
 '[rec]³ 3 génesis (2012)',
 'a bad moms christmas (2017)',
 'a christmas story live! (2017)',
 'a cosmic christmas (1977)',
 'a detective story (2003)',
 "a dog's purpose (2017)",
 'a flintstones christmas carol (1994)',
 'a german life (2016)',
 'a home at the end of the world (2004)',
 'a man called blade (1977)',
 'a man from boulevard des capucines (1987)',
 "a merry friggin' christmas (2014)",
 "a midsummer night's dream (2016)",
 'a million ways to die in the west (2014)',
 'a most wanted man (2014)',
 'a perfect day (2015)',
 'a pigeon sat on a branch reflecting on existence (2014)',
 'a plasticine crow (1981)',
 'a quiet place (2018)',
 'a silent voice (2016)',
 'a story of children and film (2013)',
 'a street cat named bob (2016)',
 'a very murray christmas (2015)',
 'a walk in the woods (2015)',
 'a wrinkle in time (2018)',
 'a-team, the (2010)',
 'a.i. artificial intelligence (2001)',
 'abandoned, the (2006)',
 'abbott and costello meet frankenstein (1948)',
 'abcs of death, the (2012)',
 'abduction (2011)',
 'abominable dr. phibes, the (1971)',
 'abominable snowman, the (abominable snowman of the himalayas, the) (1957)',
 'about a boy (2002)',
 'about adam (2000)',
 'about last night (2014)',
 'about last night... (1986)',
 'about schmidt (2002)',
 'about time (2013)',
 'above the law (1988)',
 'above the rim (1994)',
 'abraham lincoln: vampire hunter (2012)',
 'absence of malice (1981)',
 'absent-minded professor, the (1961)',
 'absentia (2011)',
 'absolute power (1997)',
 'absolutely anything (2015)',
 'abyss, the (1989)',
 'accepted (2006)',
 'accidental spy, the (dak miu mai shing) (2001)',
 'accidental tourist, the (1988)',
 'accused, the (1988)',
 'ace in the hole (big carnival, the) (1951)',
 'ace ventura: pet detective (1994)',
 'ace ventura: when nature calls (1995)',
 'aces: iron eagle iii (1992)',
 'acid house, the (1998)',
 'across the hall (2009)',
 'across the universe (2007)',
 'act of killing, the (2012)',
 'act of valor (2012)',
 'action jackson (1988)',
 "adam and eve (national lampoon's adam & eve) (2005)",
 "adam's apples (adams æbler) (2005)",
 "adam's rib (1949)",
 'adanggaman (2000)',
 'adaptation (2002)',
 'addams family reunion (1998)',
 'addams family values (1993)',
 'addams family, the (1991)',
 'addicted to love (1997)',
 'addiction, the (1995)',
 'adjustment bureau, the (2011)',
 'admission (2013)',
 'adventureland (2009)',
 'adventures in babysitting (1987)',
 'adventures in plymptoons! (2011)',
 'adventures of baron munchausen, the (1988)',
 'adventures of buckaroo banzai across the 8th dimension, the (1984)',
 'adventures of elmo in grouchland, the (1999)',
 'adventures of ford fairlane, the (1990)',
 'adventures of huck finn, the (1993)',
 'adventures of ichabod and mr. toad, the (1949)',
 'adventures of mary-kate and ashley, the: the case of the christmas caper (1995)',
 'adventures of milo and otis, the (koneko monogatari) (1986)',
 'adventures of mowgli: the kidnapping (1968)',
 'adventures of pinocchio, the (1996)',
 'adventures of pluto nash, the (2002)',
 'adventures of priscilla, queen of the desert, the (1994)',
 'adventures of robin hood, the (1938)',
 'adventures of rocky and bullwinkle, the (2000)',
 'adventures of sebastian cole, the (1998)',
 'adventures of sharkboy and lavagirl 3-d, the (2005)',
 'adventures of sherlock holmes and dr. watson: the twentieth century approaches (1986)',
 'adventures of tintin, the (2011)',
 'advise and consent (1962)',
 'aelita: the queen of mars (aelita) (1924)',
 'aeon flux (2005)',
 'affair of love, an (liaison pornographique, une) (1999)',
 'affair of the necklace, the (2001)',
 'affair to remember, an (1957)',
 'afflicted (2013)',
 'affliction (1997)',
 'afonya (1975)',
 'africa: the serengeti (1994)',
 'african cats (2011)',
 'african queen, the (1951)',
 'afro samurai (2007)',
 'afro samurai: resurrection (2009)',
 'after earth (2013)',
 'after hours (1985)',
 'after life (wandafuru raifu) (1998)',
 'after the fox (caccia alla volpe) (1966)',
 'after the sunset (2004)',
 'after the thin man (1936)',
 'after the wedding (efter brylluppet) (2006)',
 'afterglow (1997)',
 'against all odds (1984)',
 'against the ropes (2004)',
 'age of innocence, the (1993)',
 'agent cody banks (2003)',
 'agent cody banks 2: destination london (2004)',
 'agnes of god (1985)',
 'agony and the ecstasy, the (1965)',
 'agora (2009)',
 'aguirre: the wrath of god (aguirre, der zorn gottes) (1972)',
 'aileen: life and death of a serial killer (2003)',
 'air america (1990)',
 'air bud (1997)',
 'air bud: golden receiver (1998)',
 'air force one (1997)',
 'air i breathe, the (2007)',
 'air up there, the (1994)',
 'airborne (1993)',
 'airheads (1994)',
 'airplane ii: the sequel (1982)',
 'airplane! (1980)',
 "airport '77 (1977)",
 'airport (1970)',
 'airport 1975 (1974)',
 'akeelah and the bee (2006)',
 'akira (1988)',
 "akira kurosawa's dreams (dreams) (1990)",
 'aladdin (1992)',
 'aladdin and the king of thieves (1996)',
 'alamo, the (1960)',
 'alan partridge: alpha papa (2013)',
 'alaska (1996)',
 'alaska: spirit of the wild (1997)',
 'albatross (2011)',
 'albino alligator (1996)',
 'alesha popovich and tugarin the dragon (2004)',
 'alex and emma (2003)',
 'alex cross (2012)',
 'alexander (2004)',
 'alexander nevsky (aleksandr nevskiy) (1938)',
 'alfie (1966)',
 'alfie (2004)',
 'ali (2001)',
 'ali g indahouse (2002)',
 'ali wong: baby cobra (2016)',
 'ali: fear eats the soul (angst essen seele auf) (1974)',
 'alias betty (betty fisher et autres histoires) (2001)',
 'alice (1990)',
 'alice (2009)',
 'alice (neco z alenky) (1988)',
 'alice adams (1935)',
 "alice doesn't live here anymore (1974)",
 'alice in wonderland (1933)',
 'alice in wonderland (1951)',
 'alice in wonderland (2010)',
 'alice through the looking glass (2016)',
 'alien (1979)',
 'alien contamination (1980)',
 'alien from l.a. (1988)',
 'alien nation (1988)',
 'alien: covenant (2017)',
 'alien: resurrection (1997)',
 'aliens (1986)',
 'alien³ (a.k.a. alien 3) (1992)',
 'alive (1993)',
 'all about eve (1950)',
 'all about lily chou-chou (riri shushu no subete) (2001)',
 'all about my mother (todo sobre mi madre) (1999)',
 'all about the benjamins (2002)',
 'all dogs christmas carol, an (1998)',
 'all dogs go to heaven (1989)',
 'all dogs go to heaven 2 (1996)',
 'all good things (2010)',
 'all is bright (2013)',
 'all is lost (2013)',
 'all of me (1984)',
 'all or nothing (2002)',
 'all over the guy (2001)',
 'all quiet on the western front (1930)',
 'all roads lead to rome (2016)',
 'all that heaven allows (1955)',
 'all that jazz (1979)',
 'all the boys love mandy lane (2006)',
 "all the king's men (1949)",
 "all the king's men (2006)",
 "all the president's men (1976)",
 'all the pretty horses (2000)',
 'all the real girls (2003)',
 'all the right moves (1983)',
 'all the vermeers in new york (1990)',
 'all this, and heaven too (1940)',
 'all watched over by machines of loving grace (2011)',
 'all yours (2016)',
 'all-star superman (2011)',
 'allan quatermain and the lost city of gold (1987)',
 'allegro non troppo (1977)',
 'alles inklusive (2014)',
 'alligator (1980)',
 'allnighter, the (1987)',
 'almost an angel (1990)',
 'almost famous (2000)',
 'almost heroes (1998)',
 'aloha (2015)',
 'alone in the dark (2005)',
 'alone in the dark ii (2008)',
 'along came a spider (2001)',
 'along came polly (2004)',
 'alpha (2018)',
 'alpha and omega 3: the great wolf games (2014)',
 'alpha dog (2007)',
 'alphaville (alphaville, une étrange aventure de lemmy caution) (1965)',
 'altered (2006)',
 'altered states (1980)',
 'alvarez kelly (1966)',
 'alvin and the chipmunks (2007)',
 'alvin and the chipmunks: chipwrecked (2011)',
 'alvin and the chipmunks: the squeakquel (2009)',
 'always (1989)',
 'always watching: a marble hornets story (2015)',
 'amadeus (1984)',
 'amanda knox (2016)',
 'amarcord (1973)',
 'amateur (1994)',
 'amazing grace (2006)',
 'amazing grace and chuck (1987)',
 'amazing panda adventure, the (1995)',
 'amazing spider-man, the (2012)',
 'amazing transparent man, the (1960)',
 'amazon women on the moon (1987)',
 "amelie (fabuleux destin d'amélie poulain, le) (2001)",
 'amen. (2002)',
 'amer (2009)',
 "america's sweethearts (2001)",
 'american astronaut, the (2001)',
 'american beauty (1999)',
 'american buffalo (1996)',
 'american carol, an (2008)',
 'american dreamz (2006)',
 'american drug war: the last white hope (2007)',
 'american fable (2017)',
 'american flyers (1985)',
 'american friend, the (amerikanische freund, der) (1977)',
 'american gangster (2007)',
 'american gigolo (1980)',
 'american graffiti (1973)',
 'american grindhouse (2010)',
 'american hardcore (2006)',
 'american haunting, an (2005)',
 'american heist (2015)',
 'american history x (1998)',
 'american hustle (2013)',
 'american in paris, an (1951)',
 'american made (2017)',
 'american me (1992)',
 'american movie (1999)',
 'american ninja (1985)',
 'american outlaws (2001)',
 'american pie (1999)',
 'american pie 2 (2001)',
 'american pie presents beta house (american pie 6: beta house) (2007)',
 'american pie presents the naked mile (american pie 5: the naked mile) (2006)',
 'american pie presents: band camp (american pie 4: band camp) (2005)',
 'american pie presents: the book of love (american pie 7: the book of love) (2009)',
 'american pop (1981)',
 'american president, the (1995)',
 'american psycho (2000)',
 'american psycho ii: all american girl (2002)',
 'american reunion (american pie 4) (2012)',
 'american sniper (2014)',
 'american splendor (2003)',
 'american tail, an (1986)',
 'american tail: fievel goes west, an (1991)',
 'american ultra (2015)',
 'american wedding (american pie 3) (2003)',
 'american werewolf in london, an (1981)',
 'american werewolf in paris, an (1997)',
 'american, the (2010)',
 'american: the bill hicks story (2009)',
 'americanization of emily, the (1964)',
 'americathon (1979)',
 'amistad (1997)',
 "amityville 1992: it's about time (1992)",
 'amityville 3-d (1983)',
 'amityville curse, the (1990)',
 'amityville horror, the (1979)',
 'amityville horror, the (2005)',
 'amityville ii: the possession (1982)',
 'amityville: a new generation (1993)',
 'amityville: dollhouse (1996)',
 "amores perros (love's a bitch) (2000)",
 'amos & andrew (1993)',
 'amy (2015)',
 "amy's o (a.k.a. amy's orgasm) (2001)",
 'an amazing couple (2002)',
 'anacleto: agente secreto (2015)',
 'anaconda (1997)',
 'anaconda: the offspring (2008)',
 'anacondas: the hunt for the blood orchid (2004)',
 'analyze that (2002)',
 'analyze this (1999)',
 'anarchist cookbook, the (2002)',
 'anastasia (1956)',
 'anastasia (1997)',
 'anatomy of a murder (1959)',
 'anchorman 2: the legend continues (2013)',
 'anchorman: the legend of ron burgundy (2004)',
 'anchors aweigh (1945)',
 'and god created woman (et dieu... créa la femme) (1956)',
 'and now... ladies and gentlemen... (2002)',
 'and so it goes (2014)',
 'and starring pancho villa as himself (2003)',
 'and the band played on (1993)',
 'and the ship sails on (e la nave va) (1983)',
 'and then there were none (1945)',
 'and your mother too (y tu mamá también) (2001)',
 'andalusian dog, an (chien andalou, un) (1929)',
 'andre (1994)',
 'andrei rublev (andrey rublyov) (1969)',
 'andrew dice clay: dice rules (1991)',
 'android (1982)',
 'andromeda strain, the (1971)',
 'angel at my table, an (1990)',
 'angel baby (1995)',
 'angel eyes (2001)',
 'angel heart (1987)',
 "angel's egg (tenshi no tamago) (1985)",
 'angel-a (2005)',
 "angela's ashes (1999)",
 'angels & demons (2009)',
 'angels and insects (1995)',
 'angels in the outfield (1994)',
 'angels with dirty faces (1938)',
 "angels' share, the (2012)",
 'anger management (2003)',
 'angie (1994)',
 'angriest man in brooklyn, the (2014)',
 'angry red planet, the (1959)',
 'angst  (1983)',
 'angus (1995)',
 'angus, thongs and perfect snogging (2008)',
 'animal crackers (1930)',
 'animal factory (2000)',
 'animal farm (1954)',
 'animal house (1978)',
 'animal, the (2001)',
 'animals are beautiful people (1974)',
 'animatrix, the (2003)',
 'anna and the king (1999)',
 'anna christie (1930)',
 'anna karenina (1935)',
 'anna karenina (1997)',
 'anna karenina (2012)',
 'annabelle (2014)',
 'annabelle: creation (2017)',
 'annapolis (2006)',
 'anne frank remembered (1995)',
 'anne of green gables (1985)',
 'anne of green gables: the sequel (a.k.a. anne of avonlea) (1987)',
 'anne of the thousand days (1969)',
 'annie (1982)',
 'annie get your gun (1950)',
 'annie hall (1977)',
 'annihilation (2018)',
 'anniversary party, the (2001)',
 'anohana: the flower we saw that day - the movie (2013)',
 'anomalisa (2015)',
 'another 48 hrs. (1990)',
 'another cinderella story (2008)',
 'another earth (2011)',
 'another gay movie (2006)',
 'another stakeout (1993)',
 'another thin man (1939)',
 'another woman (1988)',
 'ant bully, the (2006)',
 'ant-man (2015)',
 'ant-man and the wasp (2018)',
 'anthony adverse (1936)',
 'anti-social (2015)',
 'antichrist (2009)',
 'antitrust (2001)',
 "antonia's line (antonia) (1995)",
 'antonio gaudí (1985)',
 'antwone fisher (2002)',
 'antz (1998)',
 'anvil! the story of anvil (2008)',
 'any given sunday (1999)',
 'any which way you can (1980)',
 'anything else (2003)',
 'anything for her (pour elle) (2008)',
 'anything for love (2016)',
 'anywhere but here (1999)',
 'apartment, the (1960)',
 "apartment, the (appartement, l') (1996)",
 'apocalypse now (1979)',
 'apocalypto (2006)',
 'apollo 13 (1995)',
 'apollo 18 (2011)',
 'apostle, the (1997)',
 'appaloosa (2008)',
 'apple dumpling gang rides again, the (1979)',
 'apple dumpling gang, the (1975)',
 'apple, the (sib) (1998)',
 'applesauce (2015)',
 'appleseed (appurushîdo) (2004)',
 "april fool's day (1986)",
 'april morning (1988)',
 'apt pupil (1998)',
 'aqua teen hunger force colon movie film for theaters (2007)',
 'aquamarine (2006)',
 'arachnophobia (1990)',
 'ararat (2002)',
 'are we done yet? (2007)',
 'are we there yet? (2005)',
 'are you scared? (2006)',
 'argo (2012)',
 'ari shaffir: double negative (2017)',
 'ariel (1988)',
 'aristocats, the (1970)',
 'aristocrats, the (2005)',
 'arizona dream (1993)',
 'arlington road (1999)',
 'armageddon (1998)',
 'armed and dangerous (1986)',
 'armour of god (long xiong hu di) (1987)',
 'armour of god ii: operation condor (operation condor) (fei ying gai wak) (1991)',
 'army of darkness (1993)',
 "army of shadows (l'armée des ombres) (1969)",
 'around the world in 80 days (1956)',
 'around the world in 80 days (2004)',
 'arq (2016)',
 'arrival (2016)',
 'arrival, the (1996)',
 'arsenic and old lace (1944)',
 'art of getting by, the (2011)',
 'art of the steal, the (2009)',
 'art of the steal, the (2013)',
 'art of war, the (2000)',
 'art school confidential (2006)',
 'artemisia (1997)',
 'arthur (1981)',
 'arthur (2011)',
 'arthur 2: on the rocks (1988)',
 'arthur christmas (2011)',
 'as above, so below (2014)',
 'as good as it gets (1997)',
 'as i was moving ahead occasionally i saw brief glimpses of beauty (2000)',
 'as you like it (2006)',
 'ascent, the (voskhozhdeniye) (1977)',
 'ashby (2015)',
 'ashes and diamonds (popiól i diament) (1958)',
 'ashes of time (dung che sai duk) (1994)',
 'ask the dust (2006)',
 'aspen extreme (1993)',
 'asphalt jungle, the (1950)',
 'asphyx, the (1973)',
 "assassin's creed (2016)",
 'assassination (1987)',
 'assassination of a high school president (2008)',
 'assassination of jesse james by the coward robert ford, the (2007)',
 'assassination of richard nixon, the (2004)',
 'assassination tango (2002)',
 'assassins (1995)',

In [21]:
columns = []
for i in cols:
    columns.append(i.lower())
movieTitle.columns = columns

In [22]:
movieTitle.head()

,'71 (2014),"'burbs, the (1989)",'hellboy': the seeds of creation (2004),'night mother (1986),'round midnight (1986),'salem's lot (2004),'til there was you (1997),'tis the season for love (2015),(500) days of summer (2009),*batteries not included (1987),...,zookeeper (2011),zoolander (2001),zoolander 2 (2016),zoom (2006),zoom (2015),zootopia (2016),zulu (1964),zulu (2013),¡three amigos! (1986),à nous la liberté (freedom for us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
def Recommend():
    movieName = input('Enter Movie Name').lower()
    userRatings = movieTitle[movieName]
    similar_movies = movieTitle.corrwith(userRatings)
    corr_movie = pd.DataFrame(similar_movies.dropna(), columns = ['Correlation'])
    corr_movie = corr_movie.join(dfNew['NumRatings'])
    sugg = corr_movie[corr_movie['NumRatings'] > 100].sort_values('Correlation', ascending = False)
    return sugg

In [27]:
Recommend()

Enter Movie Name10 years (2011)

Empty DataFrame
Columns: [Correlation, NumRatings]
Index: []

###  Content Based Approach

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv('data.csv')
df.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [30]:
df.keys()

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [31]:
features = ['keywords', 'cast', 'genres','director']

In [32]:
for i in features:
    df[i] = df[i].fillna("")

In [33]:
def MovieCount(row):
    out = ''
    for i in features:
        out += row[i]
        out += ' '
    return out

In [34]:
df['movie_content'] = df.apply(MovieCount, axis = 1)
df['movie_content']

0       culture clash future space war space colony so...
1       ocean drug abuse exotic island east india trad...
2       spy based on novel secret agent sequel mi6 Dan...
3       dc comics crime fighter terrorist secret ident...
4       based on novel mars medallion space travel pri...
                              ...
4798    united states\u2013mexico barrier legs arms pa...
4799     Edward Burns Kerry Bish\u00e9 Marsha Dietlein...
4800    date love at first sight narration investigati...
4801     Daniel Henney Eliza Coupe Bill Paxton Alan Ru...
4802    obsession camcorder crush dream girl Drew Barr...
Name: movie_content, Length: 4803, dtype: object

In [35]:
def LowerCaseTitle(title):
    return title.lower()

In [36]:
df.title = df.title.apply(LowerCaseTitle)

In [37]:
cv = CountVectorizer()
matrix = cv.fit_transform(df.movie_content)

In [38]:
len(cv.get_feature_names())

14845

In [39]:
word_sim = cosine_similarity(matrix)
df['title'].head()

0                                      avatar
1    pirates of the caribbean: at world's end
2                                     spectre
3                       the dark knight rises
4                                 john carter
Name: title, dtype: object

In [45]:
def Recommendation():
    movie_name = input('Enter the Movie Name')
    movie_name = movie_name.lower().strip()
    m_index = df[df['title'] == movie_name]['index'].values[0]
    similar_word_value = word_sim[m_index]
    similar_movies = list(enumerate(similar_word_value))
    sorted_similar_movies = sorted(similar_movies, key = lambda x: x[1], reverse = True)
    movies_num = 5
    print("\nTop Similar Movies\n")
    for i in range(movies_num):
        index = sorted_similar_movies[i][0]
        movie = list(df[index:index+1]['title'])[0]
        print(i+1, movie)

In [46]:
Recommendation()

Enter the Movie NameAVATAR

Top Similar Movies

1 avatar
2 guardians of the galaxy
3 aliens
4 star wars: clone wars: volume 1
5 star trek into darkness

### <centre>-----------MOVIE RECOMMENDATION SYSTEM-------------</centre>

In [ ]:
############ LEMME KNOW YOUR SUGGESTION IF I CAN IMPROVE THE MDODEL ###########################################################